### ISSUE TITLE
VisualEditorEverywhere doesn't work on anchor links

### ISSUE THREAD

**Issue by FormalDude** [NovemLinguae/UserScripts#176] opened 2023-08-06 01:14 UTC
The visual editor button does not work if you navigate to a section of a page using an anchor link (a wikilink that links to a section e.g. [[page name#section name]]). 

For example, if I navigate to the "Personal life" section of [[Tom Brady]] though the table of contents, when I click the section's visual edit button, it directs me to https://en.wikipedia.org/w/index.php?title=Tom_Brady&veaction=edit&section=48&editintro=Template:BLP_editintro and produces the following error:
<img width="274" alt="image" src="https://github.com/NovemLinguae/UserScripts/assets/133025275/3c9ec7ef-78a4-42ec-a42f-ec8ccdc839f1">

Another example:

<img width="269" alt="Error Screenshot at Aug 05 19-02-03" src="https://github.com/NovemLinguae/UserScripts/assets/133025275/f80449b2-4566-4a53-916f-8e25f18d682c">

**Comment by NovemLinguae** [comment] 2023-08-06 08:50
Unable to reproduce on the Tom Brady article. Steps I'm using

* skin=vector 2010
* visit https://en.wikipedia.org/wiki/Tom_Brady
* click table of contents -> "personal life"
* click "[ Edit ]"

I did not receive any JavaScript errors. The page jumped to the correct location after the visual editor loaded.

This is a mainspace article, so may not involve my user script at all. VisualEditorEverywhere is usually for talk pages, Wikipedia space, etc.

Am I using the correct steps to reproduce above?

**Comment by NovemLinguae** [comment] 2023-08-08 20:08
Closing since this doesn't appear to involve VisualEditorEverywhere. Feel free to re-open if this isn't the case.

**Closed by NovemLinguae** 2023-08-08 20:08 UTC
